# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Sensors
sensor:
  # Weather prediction
  - platform: yr

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

input_number:
  max_temp:
    name: 'Max Temperature'
    initial: 27
    min: 24
    max: 30
    step: 1
  min_temp:
    name: 'Min Temperature'
    initial: 25
    min: 21
    max: 28
    step: 1