esphome:
  name: ac_control
  platform: ESP32
  board: esp32doit-devkit-v1

wifi: !include wifi.yml

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "***REMOVED***"

ota:
  password: "***REMOVED***"
